### PR TITLE
Final details

### PR DESCRIPTION
**Pull request by sz16900**
# Completed [Project #7 - Newsweek](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap?ref=lnav) in partial requirements of the [Microverse Curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/).

---

### Contributors:
- Seth Zea

--- 

##### General Requirements

- [x] Add a descriptive README file to your repository.
- [x] Use meaningful names for your Pull Requests and add a short summary of its content.
- [x] Use descriptive commit messages.
- [x] Do not commit files that are not related to the project. Instead, add them to .gitignore file.
- [x] Do not commit inline comments. 
- [x] Use stickler for checks.

##### Other Requirements
- [x] Keep your code clean.
- [x] Remember to use semantic HTML.
- [x] Validate your HTML markup.
- [x] Use stylelint to lint CSS files.

##### Project Specific

- [x] Remember to use Bootstrap CSS classes wherever it is possible - this is the main point of this project.
- [x] As you can use a ready set of CSS classes, be more precise and make sure that your page looks exactly the same as the source page.
- [x] Remember to double-check that your page layout does not break on smaller screens.

---
# Project Status :

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Hi @sz16900 , you have a great project! :clap: 
Let's make some changes to make it better:
1. > Reduce the font-size on the page to a similar font-size with the original.
2. > Adjust the alignment of social media icons in the footer section for small screens.
- **Yours:**
image
- **Original:**
image

3. > You have many CSS styles that could be replaced with bootstrap classes. It may be easier writing the CSS but the point of this project is to use bootstrap. Consider replacing many of them with bootstrap classes.



> The live link in your README is not available. Consider using raw.githack.com.

Please make these changes and submit another code review request.

More :muscle: !

### Status: Changes required.

**Comment by shshamim63** [comment]
## Status :eye: [!! Changes Required !!] :eye: 
___
Hi @sz16900 :wave: ,
Awesome job on this project. Contents are not overflowing. project contains a descriptive readme. Code looks neat and clean. I also double checked an issue marked by the previous reviewer. And it seems same for me too. Please take a look at the following instructions to complete the project.
___
### :point_right:  [Mandatory Changes] :point_left:
___
**:iphone: Small Screen View(470-755)Px**
1. Social icons on the footer should be vertically aligned with respect to the `Newsweek` logo. But you one does not seems like that. I know the main purpose of this project is to utilize the Bootstrap in your project. Along with that you have to mimic the page as close as you can. Take a look at the picture below to cross check:
---> Your one:
image
---> Actual one:
image
___
### :clubs: [!! Optional Changes !!] :clubs: 
___
1. You have used `display: flex`, `display: inline` property in your project. Bootstrap provides them too. You can simply call `d-flex` and `d-inline`. The more you will try to use the more you can get used to it.
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Comment by sz16900** [comment]
Thank you guys for your timely reviews. On the last comment: it seems as if I completely forgot to push the latest modified file :see_no_evil:

**Comment by Anna-Myzukina** [comment]
### Hi Seth Zea, Everything looks good :100: 
## Congratulation :+1:  Approved.
Go ahead and merge to master.
Goodluck in your next project Happy coding

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
